# Generated by Django 4.2 on 2023-04-21 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ercharacterplanner', '0002_armament_armor_ash_of_war_great_rune_spell_talisman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Starting_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Starting_Class_Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value', models.IntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ercharacterplanner.main_attribute')),
                ('starting_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ercharacterplanner.starting_class')),
            ],
        ),
        migrations.AddField(
            model_name='starting_class',
            name='attributes',
            field=models.ManyToManyField(through='ercharacterplanner.Starting_Class_Attribute', to='ercharacterplanner.main_attribute'),
        ),
    ]
