# Generated by Django 4.2 on 2023-04-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ercharacterplanner', '0004_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='starting_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ercharacterplanner.starting_class'),
        ),
    ]
