# Generated by Django 4.2 on 2023-04-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ercharacterplanner', '0005_character_starting_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ercharacterplanner.main_attribute')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ercharacterplanner.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='leveled_attributes',
            field=models.ManyToManyField(through='ercharacterplanner.Character_Attribute', to='ercharacterplanner.main_attribute'),
        ),
        migrations.AddConstraint(
            model_name='character_attribute',
            constraint=models.UniqueConstraint(fields=('character', 'attribute'), name='character_attribute_unique'),
        ),
    ]
